# Generated by Django 3.2.9 on 2023-07-22 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='todoitem',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
