# Generated by Django 3.2.9 on 2023-07-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_rename_todo_list_todoitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('w', 'Writing'), ('e', 'Editing'), ('l', 'Linkedin/Journal')], default='w', max_length=1),
            preserve_default=False,
        ),
    ]
