# Generated by Django 3.2.9 on 2023-07-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_auto_20230724_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='category',
            field=models.CharField(choices=[('n', 'Nanotechnology & Drug Delivery'), ('g', 'Gene Therapy & Genetic Medicine'), ('i', 'Infectious Disease and Microbiology'), ('r', 'RNA Therapeutics and RNA Technology'), ('u', 'Nucleic Acid Chemistry'), ('m', 'Immunotherapy and Immunology'), ('a', 'Manufacturing Technology')], default='o', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
