# Generated by Django 3.2.9 on 2023-07-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20230724_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='category',
            field=models.CharField(choices=[('n', 'Nanotechnology & Drug Delivery'), ('g', 'Gene Therapy & Genetic Medicine'), ('i', 'Infectious Disease and Microbiology'), ('r', 'RNA Therapeutics and RNA Technology'), ('u', 'Nucleic Acid Chemistry'), ('m', 'Immunotherapy and Immunology'), ('a', 'Manufacturing Technology'), ('o', 'Others')], max_length=1),
        ),
    ]
