# Generated by Django 3.2.9 on 2023-07-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_auto_20230724_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='author_cnt',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
