# Generated by Django 3.2.9 on 2023-07-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_todoitem_author_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='author_cnt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
